#!/usr/bin/env bash
# Displays "Best School" 10 times and on the 9th time says hi.

count=0

while [ $count -lt 10 ]
do
  if [ $count -eq 9 ]
  then
    echo "Hi"
  fi
  echo "Best School"
  (( count++ ))
done
