#!/usr/bin/env bash
# Display time for 12 hours and 59 minutes.
#   Display hour from 0 to 12
#   Display minute from 1 to 59

hour=0

while [ $hour -le 12 ]
do
  echo "Hour: $hour"
  minute=1
  while [ $minute -le 59 ]
  do
    echo "$minute"
    (( minute++ ))
  done
  (( hour++ ))
done
