#!/usr/bin/env bash
# Running the whoami command under the user passed as argument
if [ $# -ne 1 ]; then
  echo "Please provide one argument: the username"
  exit 1
fi

username=$1

# Run the whoami command under the specified user
su - $username -c 'whoami'

